### ISSUE TITLE
fibonacci series 

### ISSUE THREAD

**Issue by PanikaGupta** [PanikaGupta/testProject#5]

**Comment by hemantwasthere** [comment]
Hey @PanikaGupta, I would like to contribute, Can you please describe the issue

**Comment by ankit060801** [comment]
hello sir pls assign me this task

**Comment by kushagra10bansal** [comment]
Hey @PanikaGupta, i would like to contribute, could you please describe the issue and assign me this task?

**Comment by kushagra10bansal** [comment]
Hi @PanikaGupta, could you please describe the issue?

**Comment by PanikaGupta** [comment]
You just have to print Fibonacci series upto n terms. Where n should be input by user.
